let rssURLs = [
  "https://reactjs.org/",
  "https://stackoverflow.com/questions/tagged/reactjs",
  "https://egghead.io/q/react",
  "https://epicreact.dev/",
  "https://dev.to/t/react",
  "https://www.freecodecamp.org/",
  "https://pluralsight.com/",
  "https://scrimba.com/",
  "https://github.com/enaqx/awesome-react",
  "https://github.com/tiaanduplessis/awesome-react-talks",
  "https://hero35.com/",
  "https://github.com/brillout/awesome-react-components",
  "https://dev.to/davidepacilio/35-free-react-templates-and-themes-32ci",
  "https://atomizecode.com/",
  "https://treact.owaiskhan.me/",
  // "https://gatsby.ghost.org/",
  // "https://reactresources.com/",
  "https://nextjs.org/",
  "https://create-react-app.dev/",
  "https://github.com/reduxjs/react-redux",
  "https://github.com/rebassjs/rebass",
  "https://github.com/marmelab/react-admin",
  "https://github.com/ant-design/ant-design/",
  "https://github.com/grommet/grommet",
  "https://github.com/react-bootstrap/react-bootstrap",
  "https://react-dnd.github.io/react-dnd/about",
  "https://madewithreactjs.com/",
  "https://www.gatsbyjs.com/",
];
export default rssURLs;
