let rssURLs = [
  "https://www.reactathon.com/",
  "https://react-barcamp.de/",
  "https://reactconfau.com/",
  "https://reactsummit.com/",
  "https://appjs.co/",
  "https://reactday.in/",
  "https://www.renderatl.com/",
  "https://www.react-europe.org/",
  "https://react-finland.fi/",
  "https://react-next.com/",
  "https://reactloop.com/",
  "https://reactweek.nyc/",
  "https://reactnewyork.com/",
  "https://www.react.brussels/",
  "http://reactconf.com.br/",
  "https://reactadvanced.com/",
  "https://geekle.us/react",
  "https://www.reactindia.io/",
];
export default rssURLs;
